name: Docker Images

on:
  push:
    # branches:
    # - main
    # tags:
    # - v*
  pull_request:
    branches:
    - main
  schedule:
    - cron:  '1 0 * * 0'
  release:
    types: [published]
  workflow_dispatch:

jobs:

  docker:
    name: Build and publish Docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        backend: [jax, torch]
        base-image: [nvidia/cuda:11.1-cudnn8-devel-ubuntu20.04, nvidia/cuda:11.1-cudnn8-runtime-ubuntu20.04]
        exclude:
          - backend: jax
            base-image: nvidia/cuda:11.1-cudnn8-runtime-ubuntu20.04
          - backend: torch
            base-image: nvidia/cuda:11.1-cudnn8-devel-ubuntu20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=pyhf/cuda
          VERSION=latest-${{ matrix.backend }}
          PYHF_VERSION=0.6.1
          CUDA_VERSION=11.1
          FULL_TAG=${PYHF_VERSION}-${{ matrix.backend }}-cuda-${CUDA_VERSION}
          REPO_NAME=${{github.repository}}
          REPO_NAME_LOWERCASE="${REPO_NAME,,}"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          TAGS="$TAGS,${DOCKER_IMAGE}:latest-${{ matrix.backend }},${DOCKER_IMAGE}:${FULL_TAG},${DOCKER_IMAGE}:sha-${GITHUB_SHA::8}"
          # Releases also have GITHUB_REFs that are tags, so reuse VERSION
          if [ "${{ github.event_name }}" = "release" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest-stable-${{ matrix.backend }},ghcr.io/${REPO_NAME_LOWERCASE}:latest-stable-${{ matrix.backend }},ghcr.io/${REPO_NAME_LOWERCASE}:${VERSION}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=repo_name_lowercase::"${REPO_NAME_LOWERCASE}"
          echo ::set-output name=full_tag::"${FULL_TAG}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Test build
        id: docker_build_test
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.prep.outputs.tags }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
            PYHF_BACKEND=${{ matrix.backend }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          load: true
          push: false

      - name: Image digest
        run: echo ${{ steps.docker_build_test.outputs.digest }}

      - name: List built images
        run: docker images

      - name: Build and publish to registry
        # every PR will trigger a push event on main, so check the push event is actually coming from main
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'pyhf/cuda-images'
        id: docker_build_latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
            PYHF_BACKEND=${{ matrix.backend }}
          tags: |
            pyhf/cuda:latest-${{ matrix.backend }}
            pyhf/cuda:${{ steps.prep.outputs.full_tag }}
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:latest-${{ matrix.backend }}
            ghcr.io/${{ steps.prep.outputs.repo_name_lowercase }}:${{ steps.prep.outputs.full_tag }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true

      - name: Build and publish to registry with release tag
        if: github.event_name == 'release' && github.event.action == 'published' && github.repository == 'pyhf/cuda-images'
        id: docker_build_release
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
            PYHF_BACKEND=${{ matrix.backend }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          push: true
